Page layout
franklinben23/leaderboard-list pull request #1
Opened 2021-12-17 23:27 UTC by franklinben23

In this branch I created and added the layout of the page of the application.

2021-12-17 23:47 UTC, rloterh requested changes
Hi Franklin, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦 🚦  

## Good Points 👍  
- Descriptive Pull Request
- No linter errors


## Required Changes ♻️
_Kindly check the comments under the review._

<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-17 23:47 UTC, rloterh commented on package.json
>    },
- [ ] On line 6, the _script option_ of your _package.json_ file is **not properly configured** and hence your application cannot start using the command `npm start`. Kindly add the necessary _script options_ similar to as can be seen below:

```json
  "scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack --config webpack.config.js --watch"
  }
```

2021-12-17 23:47 UTC, rloterh commented on package.json
>    },
- [ ] The _dervServer_ package is missing your application. Kindly install the same and add that in your **webpack** configuration to enable your application to be run on the server locally.

**devServer in webpack configuration file:**
![image](https://user-images.githubusercontent.com/12745474/134922749-d0016f56-002e-4415-8882-4eb3dcbf6551.png)

2021-12-18 01:15 UTC, mke2111 approved these changes
### Hi @franklinben23, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
**Congratulations! 🎉** 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-18 01:58 UTC, merged